export const PED_COMPONENTS_IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

export const PED_PROPS_IDS = [0, 1, 2, 6, 7];

export const FACE_FEATURES: Array<keyof PedFaceFeatures> = [
  'noseWidth',
  'nosePeakHigh',
  'nosePeakSize',
  'noseBoneHigh',
  'nosePeakLowering',
  'noseBoneTwist',
  'eyeBrownHigh',
  'eyeBrownForward',
  'cheeksBoneHigh',
  'cheeksBoneWidth',
  'cheeksWidth',
  'eyesOpening',
  'lipsThickness',
  'jawBoneWidth',
  'jawBoneBackSize',
  'chinBoneLowering',
  'chinBoneLenght',
  'chinBoneSize',
  'chinHole',
  'neckThickness',
];

export const HEAD_OVERLAYS = [
  'blemishes',
  'beard',
  'eyebrows',
  'ageing',
  'makeUp',
  'blush',
  'complexion',
  'sunDamage',
  'lipstick',
  'moleAndFreckles',
  'chestHair',
  'bodyBlemishes',
];

// Thanks to rootcause for the eye colors names and hair decorations hashes.
export const EYE_COLORS: string[] = [
  'Green',
  'Emerald',
  'Light Blue',
  'Ocean Blue',
  'Light Brown',
  'Dark Brown',
  'Hazel',
  'Dark Gray',
  'Light Gray',
  'Pink',
  'Yellow',
  'Purple',
  'Blackout',
  'Shades of Gray',
  'Tequila Sunrise',
  'Atomic',
  'Warp',
  'ECola',
  'Space Ranger',
  'Ying Yang',
  'Bullseye',
  'Lizard',
  'Dragon',
  'Extra Terrestrial',
  'Goat',
  'Smiley',
  'Possessed',
  'Demon',
  'Infected',
  'Alien',
  'Undead',
  'Zombie',
];

export const HARDCODED_MALE_HAIR_DECORATIONS = new Map<number, HardcodedHairDecoration>([
  [0, { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' }],
  [1, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_001' }],
  [2, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_002' }],
  [3, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_003' }],
  [4, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_004' }],
  [5, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_005' }],
  [6, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_006' }],
  [7, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_007' }],
  [8, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_008' }],
  [9, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_009' }],
  [10, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_013' }],
  [11, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_002' }],
  [12, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_011' }],
  [13, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_012' }],
  [14, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' }],
  [15, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' }],
  [16, { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_000' }],
  [17, { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_001' }],
  [18, { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_000' }],
  [19, { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_001' }],
  [20, { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_000' }],
  [21, { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_001' }],
  [22, { collection: 'multiplayer_overlays', overlay: 'NGInd_M_Hair_000' }],
  [24, { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_000' }],
  [25, { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_001' }],
  [26, { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_002' }],
  [27, { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_003' }],
  [28, { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_004' }],
  [29, { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_005' }],
  [30, { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_006' }],
  [31, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_M' }],
  [32, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_M' }],
  [33, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_M' }],
  [34, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_M' }],
  [35, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_M' }],
  [36, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_005_M' }],
  [72, { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_M_000_M' }],
  [73, { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_M_001_M' }],
  [74, { collection: 'mpVinewood_overlays', overlay: 'MP_Vinewood_Hair_M_000_M' }],
]);

export const HARDCODED_FEMALE_HAIR_DECORATIONS = new Map<number, HardcodedHairDecoration>([
  [0, { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' }],
  [1, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_001' }],
  [2, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_002' }],
  [3, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_003' }],
  [4, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_004' }],
  [5, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_005' }],
  [6, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_006' }],
  [7, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_007' }],
  [8, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_008' }],
  [9, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_009' }],
  [10, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_010' }],
  [11, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_011' }],
  [12, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_012' }],
  [13, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_013' }],
  [14, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' }],
  [15, { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' }],
  [16, { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_000' }],
  [17, { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_001' }],
  [18, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_007' }],
  [19, { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_000' }],
  [20, { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_001' }],
  [21, { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_001' }],
  [22, { collection: 'multiplayer_overlays', overlay: 'NGHip_F_Hair_000' }],
  [23, { collection: 'multiplayer_overlays', overlay: 'NGInd_F_Hair_000' }],
  [25, { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_000' }],
  [26, { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_001' }],
  [27, { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_002' }],
  [28, { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_003' }],
  [29, { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_003' }],
  [30, { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_004' }],
  [31, { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_006' }],
  [32, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_F' }],
  [33, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_F' }],
  [34, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_F' }],
  [35, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_F' }],
  [36, { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_003' }],
  [37, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_006_F' }],
  [38, { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_F' }],
  [76, { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_F_000_F' }],
  [77, { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_F_001_F' }],
  [78, { collection: 'mpVinewood_overlays', overlay: 'MP_Vinewood_Hair_F_000_F' }],
]);

export const DEFAULT_CUSTOMIZATION_CONFIG: CustomizationConfig = {
  ped: true,
  headBlend: true,
  faceFeatures: true,
  headOverlays: true,
  components: true,
  props: true,
};
